#' Get the list of project
#'
#' @param token a token of class `collab_token`
#'
#' @importFrom attempt stop_if_not
#' @importFrom httr GET
#' @importFrom tibble as_tibble
#' @importFrom purrr modify_depth map_df
#'
#' @return a tibble
#' @export
#'
#' @examples
#' \dontrun{
#' get_projects_list(my_token)
#' }

get_projects_list <- function(token){
  attempt::stop_if_not(
    token,
    ~ class(.x) == "collab_token",
    "Please provide an access token generated by get_active_collab_token()"
  )
  res <- GET(
    glue("https://app.activecollab.com/{token$app_id}/api/v1/projects"),
    add_headers("X-Angie-AuthApiToken" = token$token)
  ) %>% content()

  res <- modify_depth(
    res,
    2,
    ~ ifelse(is.null(.x), NA, .x)
  )

  map_df(res, as_tibble)
}

