#' @import crul

new_collab_con <- function(token, extension){
  HttpClient$new(
    url = glue("https://app.activecollab.com/{token$app_id}/api/v1/{extension}"),
    headers = list("X-Angie-AuthApiToken" = token$token))
}


#' @importFrom jsonlite fromJSON

get_endpoint <- function(token, extension){
  endpoint <- new_collab_con(token, extension)
  endpoint <- endpoint$get()

  endpoint$content %>% rawToChar() %>% fromJSON()
}

#' @importFrom attempt stop_if_not

stop_if_not_collab <- function(token){
  stop_if_not(
    token,
    ~ class(.x) == "collab_token",
    "Please provide an access token generated by get_active_collab_token()"
  )
}
